Added new emerald pipeline files

diff --git a/.github/workflows/UIBuildAndPush.yml b/.github/workflows/UIBuildAndPush.yml
--- a/.github/workflows/UIBuildAndPush.yml
+++ b/.github/workflows/UIBuildAndPush.yml
@@ -1,4 +1,4 @@
-name: "STRDSS Server"
+name: "JUSTIN Custom Claim"
 
 on:
   push:
@@ -16,17 +16,15 @@ on:
       - main
 
 jobs:
-  server-build-and-push:
-    name: strdss-server
+  custom-claim:
+    name: custom-claim
     runs-on: ubuntu-latest
-    timeout-minutes: 10
     env:
-      working-directory: ./src/server
-      GITHUB_TOKEN: ${{ secrets.GITOPS }}
+      working-directory: ./src/DIAM.Justin.CustomClaim.Api
+      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
     steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
+      - uses: actions/checkout@v2
 
       - name: Setup .NET 7
         uses: actions/setup-dotnet@v1
@@ -36,7 +34,7 @@ jobs:
       - uses: azure/setup-helm@v3
         with:
           version: "latest " # default is latest (stable)
-          token: ${{ secrets.GITOPS }} # only needed if version is 'latest'
+          token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'
         id: install
 
       - name: Install dependencies
@@ -64,7 +62,7 @@ jobs:
         uses: "marvinpinto/action-automatic-releases@latest"
         if: startsWith(github.ref, 'refs/tags/')
         with:
-          repo_token: "${{ secrets.GITOPS }}"
+          repo_token: "${{ secrets.GITHUB_TOKEN }}"
           automatic_release_tag: "latest"
           prerelease: true
           title: "Development Build"
@@ -83,8 +81,8 @@ jobs:
         uses: docker/login-action@v1
         with:
           registry: artifacts.developer.gov.bc.ca
-          username: ${{ secrets.JFROG_USERNAME }}
-          password: ${{ secrets.JFROG_PASSWORD }}
+          username: ${{ secrets.ARTIFACTORY_USERNAME }}
+          password: ${{ secrets.ARTIFACTORY_PASSWORD }}
 
       - name: Extract metadata for Docker
         id: meta
@@ -92,7 +90,7 @@ jobs:
         if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags/')
         with:
           images: |
-            artifacts.developer.gov.bc.ca/sf4a-strdss/server
+            artifacts.developer.gov.bc.ca/je84-lea/justincustomclaimapi
           tags: |
             type=sha,format=short,prefix=dev-
             
@@ -102,7 +100,7 @@ jobs:
         if: github.ref == 'refs/heads/test' || startsWith(github.ref, 'refs/tags/')
         with:
           images: |
-            artifacts.developer.gov.bc.ca/sf4a-strdss/server
+            artifacts.developer.gov.bc.ca/je84-lea/justincustomclaimapi
           tags: |
             type=sha,format=short,prefix=test-
 
@@ -112,7 +110,7 @@ jobs:
         if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
         with:
           images: |
-            artifacts.developer.gov.bc.ca/sf4a-strdss/server
+            artifacts.developer.gov.bc.ca/je84-lea/justincustomclaimapi
           tags: |
             type=sha,format=short,prefix=prod-
             
@@ -142,9 +140,9 @@ jobs:
         if: steps.publish.outcome == 'success'
         uses: actions/checkout@v4
         with:
-          repository: bcgov-c/tenant-gitops-b0471a
+          repository: bcgov-c/tenant-gitops-bfc5f3
           ref: develop
-          token: ${{ secrets.GITOPS }} # `GITOPS` is a secret that contains your PAT
+          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
           path: gitops
 
       - name: Update Helm Values and Commit
@@ -154,7 +152,7 @@ jobs:
 
           ls -A gitops/
           # Navigate to the directory containing your Helm values file for the environment develop -> DEV, test -> test and 
-          cd gitops/charts/server
+          cd gitops/charts/justin-custom-claim-api
 
           IMAGE="${{ steps.meta.outputs.tags || steps.meta-test.outputs.tags || steps.meta-prod.outputs.tags  }} "
           IMAGE_TAG=$(echo "$IMAGE" | awk -F':' '{print $NF}')
@@ -193,49 +191,49 @@ jobs:
           # Repackage Helm Chart
           cd ../gitops/charts          
 
-          helm package ../../server/
+          helm package ../../justin-custom-claim-api/
 
           git add .
 
           git commit -m "Update image tag to $IMAGE_TAG on $DATETIME"
           git push origin develop  # Update the branch name as needed
 
-        # Update API Specification in the service registry - RBA skip for initial implmentation
-      # - name: Publish API Specification
-      #   if: steps.helm.outcome == 'success'
-      #   run: |
-      #     set -e  # Exit on error
+        # Update API Specification in the service registry
+      - name: Publish API Specification
+        if: steps.helm.outcome == 'success'
+        run: |
+          set -e  # Exit on error
 
-      #     IMAGE="${{ steps.meta.outputs.tags || steps.meta-test.outputs.tags || steps.meta-prod.outputs.tags  }} "
-      #     IMAGE_TAG=$(echo "$IMAGE" | awk -F':' '{print $NF}')
+          IMAGE="${{ steps.meta.outputs.tags || steps.meta-test.outputs.tags || steps.meta-prod.outputs.tags  }} "
+          IMAGE_TAG=$(echo "$IMAGE" | awk -F':' '{print $NF}')
 
-      #     echo $IMAGE_TAG
+          echo $IMAGE_TAG
 
-      #     # Get access token from auth endpoint 
+          # Get access token from auth endpoint 
 
-      #     export TOKEN=$(curl -X POST \
-      #       ${{ secrets.AUTH_TOKEN_ENDPOINT }} \
-      #       -H 'Content-Type: application/x-www-form-urlencoded' \
-      #       -d grant_type=client_credentials \
-      #       -d client_id=${{ secrets.REGISTRY_CLIENT_ID }} \
-      #       -d client_secret=${{ secrets.REGISTRY_CLIENT_SECRET }} | jq -r '.access_token')
-      #     echo "Access Token: $TOKEN"
+          export TOKEN=$(curl -X POST \
+            ${{ secrets.AUTH_TOKEN_ENDPOINT }} \
+            -H 'Content-Type: application/x-www-form-urlencoded' \
+            -d grant_type=client_credentials \
+            -d client_id=${{ secrets.REGISTRY_CLIENT_ID }} \
+            -d client_secret=${{ secrets.REGISTRY_CLIENT_SECRET }} | jq -r '.access_token')
+          echo "Access Token: $TOKEN"
 
-      #     http_response=$(curl -s -o response.txt -w "%{http_code}" -X POST \
-      #       -H "Authorization: Bearer $TOKEN" \
-      #       -H "Content-type: application/json; artifactType=OPENAPI" \
-      #       -H "Authorization: Bearer $TOKEN" \
-      #       -H "X-Registry-ArtifactId: justin-claim" \
-      #       -d @CustomClaimApiSpec.json  \
-      #       ${{ secrets.SERVICE_REGISTRY_HOST_URL }}/apis/registry/v2/groups/JUSTIN/artifacts?ifExists=UPDATE)
-      #       if [ $http_response != "200" ]; then
-      #           echo "Error: Failed to publish artifacts"
+          http_response=$(curl -s -o response.txt -w "%{http_code}" -X POST \
+            -H "Authorization: Bearer $TOKEN" \
+            -H "Content-type: application/json; artifactType=OPENAPI" \
+            -H "Authorization: Bearer $TOKEN" \
+            -H "X-Registry-ArtifactId: justin-claim" \
+            -d @CustomClaimApiSpec.json  \
+            ${{ secrets.SERVICE_REGISTRY_HOST_URL }}/apis/registry/v2/groups/JUSTIN/artifacts?ifExists=UPDATE)
+            if [ $http_response != "200" ]; then
+                echo "Error: Failed to publish artifacts"
                 
-      #           echo "Server returned:"
-      #           cat response.txt  
-      #           exit 1
-      #       else
-      #           echo "Server returned:"
-      #           cat response.txt    
-      #       fi
-      #   working-directory: ${{env.working-directory}}
+                echo "Server returned:"
+                cat response.txt  
+                exit 1
+            else
+                echo "Server returned:"
+                cat response.txt    
+            fi
+        working-directory: ${{env.working-directory}}
